import React from 'react'
import { Button } from '@/components/ui/button'
import { X, ExternalLink } from 'lucide-react'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";

interface AISummaryProps {
  aiSummary: string
  setAiSummary: (summary: string) => void
}

export default function AISummary({ aiSummary, setAiSummary }: AISummaryProps) {
  if (!aiSummary) return null

  return (
    <Dialog>
      <div className="border-t border-gray-800 p-3 bg-green-900/20 border-green-500/30">
        <div className="flex items-start space-x-2">
          <div className="flex-shrink-0 mt-0.5">
            <div className="h-2 w-2 bg-green-400 rounded-full animate-pulse"></div>
          </div>
          <div className="flex-1">
            <div className="text-xs font-medium text-green-400 mb-1">AI Analysis Complete</div>
            <div className="text-sm text-green-200 truncate">{aiSummary}</div>
          </div>
          <DialogTrigger asChild>
            <Button
              size="sm"
              variant="outline"
              className="h-6 px-2 text-green-400 border-green-500/50 hover:bg-green-500/10 hover:text-green-300"
              title="View full AI output"
            >
              <ExternalLink className="h-3 w-3 mr-1" />
              Open
            </Button>
          </DialogTrigger>
          <Button
            size="sm"
            variant="ghost"
            className="h-6 w-6 p-0 text-green-400 hover:text-green-300"
            onClick={() => setAiSummary('')}
            title="Dismiss"
          >
            <X className="h-3 w-3" />
          </Button>
        </div>
      </div>
      <DialogContent className="bg-gray-900 border-gray-700 text-white">
        <DialogHeader>
          <DialogTitle>Full AI Output</DialogTitle>
          <DialogDescription>
            This is the raw summary generated by the AI assistant.
          </DialogDescription>
        </DialogHeader>
        <div className="bg-gray-800 rounded-md p-4 max-h-[60vh] overflow-y-auto">
          <pre className="text-sm text-gray-300 whitespace-pre-wrap font-mono">
            {aiSummary}
          </pre>
        </div>
      </DialogContent>
    </Dialog>
  )
} 